services:
  rosbot_xl:
    build:
      context: ./
      dockerfile: Dockerfile.hardware
    privileged: true
    volumes:
      - type: bind
        source: ./
        target: /my-volume
    command: sleep 9000
