# Quick Star
# $ docker compose -f compose.rosbot.hardware.yaml up

services:
  rosbot-xl:
    image: husarion/rosbot-xl:humble
    build:
      context: ./../
      dockerfile: ./Dockerfile.hardware
    restart: unless-stopped
    command: ros2 launch rosbot_xl_bringup bringup.launch.py

  microros:
    image: microros/micro-ros-agent:humble
    restart: unless-stopped
    command: udp4 --port 8888

  rplidar:
    image: husarion/rplidar:humble
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0
    command: ros2 launch rplidar_ros rplidar.launch.py inverted:=true
