x-net-config:
  &net-config
  network_mode: host
  ipc: host

services:
  rosbot_xl:
    image: husarion/rosbot-xl:humble
    <<: *net-config
    volumes:
    - ./lan-cyclonedds.xml:/lan-cyclonedds.xml
    command: ros2 launch rosbot_xl_bringup bringup.launch.py mecanum:=${MECANUM:-False}
