x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

services:
  microros:
    image: husarion/micro-ros-agent:humble-3.1.3-20231013-stable
    <<: *net-config
    command: ros2 run micro_ros_agent micro_ros_agent  udp4 --port 8888

  rosbot_xl:
    image: husarion/rosbot-xl:humble
    <<: *net-config
    volumes:
    - ./lan-cyclonedds.xml:/lan-cyclonedds.xml
    command: ros2 launch rosbot_xl_bringup bringup.launch.py mecanum:=${MECANUM:-False}
