# Quick Start
# Mapping:
# $ docker compose -f compose.rosbot.hardware.yaml -f compose.rosbot.mapping.yaml -f compose.rosbot.vpn.yaml up
# Or localization: 
# $ docker compose -f compose.rosbot.hardware.yaml -f compose.rosbot.localization.yaml -f compose.rosbot.vpn.yaml up

services:
  microros:
    network_mode: host
    ipc: host
    volumes:
      - ./dds-config.xml:/dds-config.xml
      - ./micro_ros_entrypoint.sh:/micro-ros_entrypoint.sh
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}

  rplidar:
    network_mode: host
    ipc: host
    volumes:
      - ./dds-config.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}

  rosbot-xl:
    network_mode: host
    ipc: host
    volumes:
      - ./dds-config.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
    depends_on:
      microros:
        condition: service_healthy
      rplidar:
        condition: service_healthy

  localization-mapping:
    network_mode: host
    ipc: host
    volumes:
      - ./dds-config.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
    depends_on:
      rosbot-xl:
        condition: service_healthy

  navigation:
    network_mode: host
    ipc: host
    volumes:
      - ./dds-config.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
    depends_on:
      localization-mapping:
        condition: service_healthy
