# Quick Star
# $ docker compose -f compose.rosbot.mapping.yaml up

services:
  navigation:
    image: husarion/navigation2:humble
    restart: unless-stopped
    volumes:
      - ./config/${NAV2_PARAMS:-nav2_params.yaml}:/nav2_params.yaml

      # modified behaviour tree that doesn't replan global path
      # (it is used only when specified by default_nav_to_pose_bt_xml parameter)
      - ./config/navigate_w_recovery.xml:/navigate_w_recovery.xml
    command: >
      ros2 launch nav2_bringup navigation_launch.py    
        params_file:=/nav2_params.yaml

  localization-mapping:
    image: husarion/slam-toolbox:humble
    container_name: slam-toolbox
    restart: unless-stopped
    volumes:
      - ./config/slam_toolbox_params.yaml:/slam_params.yaml
      - ./maps:/maps
    command: >
      ros2 launch slam_toolbox online_sync_launch.py 
        slam_params_file:=/slam_params.yaml
