x-net-config:
  &net-config
  network_mode: host
  ipc: host

services:

  rosbot-xl:
    image: husarion/rosbot-xl-manipulation:humble-1.1.2-20240515
    <<: *net-config
    devices:
      - ${MANIPULATOR_SERIAL:?err}:/dev/ttyMANIPULATOR
    volumes:
      - ./config/joy_servo.yaml:/joy_servo.yaml
    command: >
      ros2 launch rosbot_xl_manipulation_bringup bringup.launch.py
        mecanum:=${MECANUM:?False}
        joy_servo_params_file:=/joy_servo.yaml
