# Quick Start
# $ docker compose -f compose.rosbot.hardware.yaml -f compose.rosbot.lan.yaml up

services:
  microros:
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID
      - RMW_IMPLEMENTATION

  rplidar:
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID
      - RMW_IMPLEMENTATION

  rosbot-xl:
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID
      - RMW_IMPLEMENTATION

  navigation:
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID
      - RMW_IMPLEMENTATION

  localization-mapping:
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID
      - RMW_IMPLEMENTATION
