# Quick Star
# $ docker compose -f compose.rosbot.localization.yaml up

services:
  localization-mapping:
    image: husarion/navigation2:humble
    restart: unless-stopped
    volumes:
      - ./config/${AMCL_PARAMS:-amcl_params.yaml}:/amcl_params.yaml
      - ./maps:/maps
    command: ros2 launch nav2_bringup localization_launch.py params_file:=/amcl_params.yaml map:=/maps/map.yaml use_sim_time:=${USE_SIM_TIME}
    healthcheck:
      test: "if [ $$(. /opt/ros/$$ROS_DISTRO/setup.sh ; ros2 topic info /map | grep 'Publisher count: 1' | wc -l) -eq 0 ]; then exit 1; else exit 0; fi"
      interval: 1s
      timeout: 5s
      retries: 50
    depends_on:
      rosbot-xl:
        condition: service_healthy

  navigation:
    # there is a problem with obstacle layer on humble
    # https://github.com/ros-planning/navigation2/issues/3014
    image: husarion/navigation2:humble
    restart: unless-stopped
    volumes:
      - ./config/${NAV2_PARAMS:-nav2_params.yaml}:/nav2_params.yaml

      # modified behaviour tree that doesn't replan global path
      # (it is used only when specified by default_nav_to_pose_bt_xml parameter)
      - ./config/navigate_w_recovery.xml:/navigate_w_recovery.xml
    command: ros2 launch nav2_bringup navigation_launch.py params_file:=/nav2_params.yaml
    healthcheck:
      test: "if [ $$(. /opt/ros/$$ROS_DISTRO/setup.sh ; ros2 topic info /local_costmap/costmap | grep 'Publisher count: 1' | wc -l) -eq 0 ]; then exit 1; else exit 0; fi"
      interval: 1s
      timeout: 5s
      retries: 50
    depends_on:
      localization-mapping:
        condition: service_healthy
