# Quick Star
# $ docker compose -f compose.rosbot.localization.yaml up

services:
  navigation:
    image: husarion/navigation2:humble
    restart: unless-stopped
    volumes:
      - ./config/${NAV2_PARAMS:-nav2_params.yaml}:/nav2_params.yaml

      # modified behaviour tree that doesn't replan global path
      # (it is used only when specified by default_nav_to_pose_bt_xml parameter)
      - ./config/navigate_w_recovery.xml:/navigate_w_recovery.xml
    command: >
      ros2 launch nav2_bringup navigation_launch.py    
        params_file:=/nav2_params.yaml

  localization-mapping:
    image: husarion/navigation2:humble
    restart: unless-stopped
    volumes:
      - ./config/amcl_params.yaml:/amcl_params.yaml
      - ./maps:/maps
    command: >
      ros2 launch nav2_bringup localization_launch.py    
        params_file:=/amcl_params.yaml
        map:=/maps/map.yaml
        use_sim_time:=${USE_SIM_TIME}
